version: '2'
services:
 postgres1:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=paint
     - POSTGRES_USER=paint
     - POSTGRES_PASSWORD=paint
     - MAX_CONNECTIONS=300
 event-store:
   image: eventstore/eventstore
   ports:
     - "2113:2113"
     - "1113:1113"
